name: oidc
on: 
  workflow_dispatch:
    inputs:
      v1:
        type: string
        default: k1
permissions:
  id-token: write
  contents: read

jobs:
  val:
   runs-on: ubuntu-latest
   steps:
     - name: echo
       run: |
          curl -sSL -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | \
          jq "{ jwt: .value, role: \"github-actions-role\" }" > ./token.json
          cat token.json

          echo 'GitHub Actions Token Claims'
          cat ./token.json | jq -r '.jwt | split(".") | .[1] | @base64d' | jq

          echo 'Vault Login Response'
          curl -sSLf -X POST -H "Content-Type: application/json" -H "X-Vault-Namespace: admin" --data @token.json http://54.70.152.70:8200/v1/auth/jwt/login

          # Remove the token file when we're done (if we don't fail)
          rm ./token.json
         
