name: oidc
on: 
  workflow_dispatch:
    inputs:
      v1:
        type: string
        default: k1
permissions:
  id-token: write
  contents: read

jobs:
  val:
   runs-on: ubuntu-latest
   steps:
     - name: echo
       run: |
         export TOKEN=$(curl -sSL -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL")
         echo $TOKEN
