name: Deployment
on: workflow_dispatch
env:
  VAULT_CLUSTER_URL: http://18.206.203.244:8200/
jobs:
  connect-list:
    runs-on: ubuntu-latest
    steps:
      - name: Import Secrets
        id: import-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: "${{ env.VAULT_CLUSTER_URL }}"
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            kv/data/user_details user_id | USER_ID ;
      - name: List Value
        run: |
         echo "User ID: $USER_ID"
