name: val
on: 
  workflow_call:
    inputs:
      v1:
        type: string
        default: k1
  workflow_dispatch:
    inputs:
      v1:
        type: string
        default: k1
jobs:
  val:
   runs-on: ubuntu-latest
   steps:
     - name: echo
       run: echo "Hello!"

